/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_pcmplayer_MainActivity */

#ifndef _Included_com_aispeech_pcmplayer_MainActivity
#define _Included_com_aispeech_pcmplayer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_pcmplayer_MainActivity
 * Method:    playPcm
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aispeech_pcmplayer_PcmPlayerActivity_playPcm
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
